### PR TITLE
Error handling specificity

### PR DESCRIPTION
**Pull request by kentbull**
This adds error handling specificity in the `IdentifierPrefix` `FromStr` implementation.

This also cleans up some IDE paths and adds them to the `.gitignore`.

### CODE REVIEW

**Review by m00sey — CHANGES_REQUESTED** [review]
You added granularity to the code, you should update the tests to test your additions.

I believe that was previously covered code.

**Comment by kentbull** [comment]
The tests I updated do target the new code I added. See the new match clauses in the assertions. I can add separate tests just for that if you would rather.On Dec 2, 2022, at 8:05 AM, Kevin Griffin ***@***.***> wrote:﻿
@m00sey requested changes on this pull request.

You added granularity to the code, you should update the tests to test your additions.
I believe that was previously covered code.

**Review by m00sey — APPROVED** [review]
wow, I'm sorry I can't believe I missed that, doing too much~

**Comment by m00sey** [comment]
Just need to fix the formatting

**Comment by kentbull** [comment]
Yeah, it is easy to miss as it’s a bit non-obvious. There was a subtle bug in the prior test code that I also missed the first time I read it. Only when I was stepping through the debugger did I find that the Deserialization error was occurring rather than a Base64Decode error.I’ll get the format update in this afternoon MST.On Dec 2, 2022, at 11:12 AM, Kevin Griffin ***@***.***> wrote:﻿
Just need to fix the formatting

**Comment by kentbull** [comment]
There are two more missing spots that came up during review where error handling is missing. They will be added tomorrow.

**Pull request merged**
